"""initial schema

Revision ID: 01853d9c14ed
Revises: 
Create Date: 2026-09-30 20:19:36.998278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01853d9c14ed'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('court_cases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cnr_number', sa.String(length=25), nullable=False),
    sa.Column('case_type', sa.String(length=100), nullable=True),
    sa.Column('case_number', sa.String(length=50), nullable=True),
    sa.Column('filing_year', sa.Integer(), nullable=True),
    sa.Column('filing_date', sa.Date(), nullable=True),
    sa.Column('registration_date', sa.Date(), nullable=True),
    sa.Column('court_type', sa.Enum('DISTRICT', 'HIGH_COURT', 'SUPREME_COURT', 'TRIBUNAL', name='courttype'), nullable=True),
    sa.Column('court_name', sa.String(length=255), nullable=True),
    sa.Column('court_complex', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('bench', sa.String(length=255), nullable=True),
    sa.Column('petitioner', sa.Text(), nullable=True),
    sa.Column('respondent', sa.Text(), nullable=True),
    sa.Column('petitioner_advocate', sa.Text(), nullable=True),
    sa.Column('respondent_advocate', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'DISPOSED', 'TRANSFERRED', 'UNKNOWN', name='casestatus'), nullable=True),
    sa.Column('next_hearing_date', sa.Date(), nullable=True),
    sa.Column('previous_hearing_date', sa.Date(), nullable=True),
    sa.Column('stage', sa.String(length=255), nullable=True),
    sa.Column('judge', sa.String(length=255), nullable=True),
    sa.Column('acts_sections', sa.JSON(), nullable=True),
    sa.Column('latest_order_date', sa.Date(), nullable=True),
    sa.Column('latest_order_link', sa.Text(), nullable=True),
    sa.Column('orders_json', sa.JSON(), nullable=True),
    sa.Column('raw_ecourts_data', sa.JSON(), nullable=True),
    sa.Column('ecourts_url', sa.Text(), nullable=True),
    sa.Column('last_polled_at', sa.DateTime(), nullable=True),
    sa.Column('poll_error_count', sa.Integer(), nullable=True),
    sa.Column('data_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_court_cases_cnr_number'), 'court_cases', ['cnr_number'], unique=True)
    op.create_index('ix_court_cases_next_hearing', 'court_cases', ['next_hearing_date'], unique=False)
    op.create_index(op.f('ix_court_cases_next_hearing_date'), 'court_cases', ['next_hearing_date'], unique=False)
    op.create_index('ix_court_cases_poll', 'court_cases', ['last_polled_at', 'poll_error_count'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('bar_registration_no', sa.String(length=50), nullable=True),
    sa.Column('state_bar_council', sa.String(length=100), nullable=True),
    sa.Column('telegram_chat_id', sa.String(length=50), nullable=True),
    sa.Column('telegram_username', sa.String(length=100), nullable=True),
    sa.Column('whatsapp_number', sa.String(length=15), nullable=True),
    sa.Column('plan', sa.Enum('FREE', 'STARTER', 'PRO', 'FIRM', name='plantier'), nullable=False),
    sa.Column('whatsapp_addon', sa.Boolean(), nullable=True),
    sa.Column('plan_expires_at', sa.DateTime(), nullable=True),
    sa.Column('max_cases', sa.Integer(), nullable=True),
    sa.Column('notification_time', sa.String(length=5), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('digest_day', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_bar_registration_no'), 'users', ['bar_registration_no'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_index(op.f('ix_users_telegram_chat_id'), 'users', ['telegram_chat_id'], unique=False)
    op.create_table('case_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('data_hash', sa.String(length=64), nullable=False),
    sa.Column('snapshot_data', sa.JSON(), nullable=False),
    sa.Column('changes', sa.JSON(), nullable=True),
    sa.Column('captured_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['court_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('channel', sa.Enum('TELEGRAM', 'EMAIL', 'WHATSAPP', name='notificationchannel'), nullable=False),
    sa.Column('notification_type', sa.Enum('WEEKLY_DIGEST', 'THREE_DAY', 'TWO_DAY', 'ONE_DAY', 'NEW_ORDER', 'CASE_UPDATE', name='notificationtype'), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('delivered', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('cost_inr', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['court_cases.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notification_log_user', 'notification_log', ['user_id', 'sent_at'], unique=False)
    op.create_table('tracked_cases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('client_name', sa.String(length=255), nullable=True),
    sa.Column('is_petitioner_side', sa.Boolean(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('notify_telegram', sa.Boolean(), nullable=True),
    sa.Column('notify_email', sa.Boolean(), nullable=True),
    sa.Column('notify_whatsapp', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['court_cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'case_id', name='uq_user_case')
    )
    op.create_index('ix_tracked_cases_user', 'tracked_cases', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tracked_cases_user', table_name='tracked_cases')
    op.drop_table('tracked_cases')
    op.drop_index('ix_notification_log_user', table_name='notification_log')
    op.drop_table('notification_log')
    op.drop_table('case_snapshots')
    op.drop_index(op.f('ix_users_telegram_chat_id'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_bar_registration_no'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_court_cases_poll', table_name='court_cases')
    op.drop_index(op.f('ix_court_cases_next_hearing_date'), table_name='court_cases')
    op.drop_index('ix_court_cases_next_hearing', table_name='court_cases')
    op.drop_index(op.f('ix_court_cases_cnr_number'), table_name='court_cases')
    op.drop_table('court_cases')
    # ### end Alembic commands ###
    for enum_name in ("plantier", "courttype", "casestatus", "notificationchannel", "notificationtype"):
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
